# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['project_root'] = project_root = File.expand_path(File.dirname(__FILE__))
ENV['valkyrie_root'] = valkyrie_root = "#{project_root}/.valkyrie/valkyrie/vagrant"
# Check that our required plugins are installed.
#require "#{valkyrie_root}/lib/plugins/plugins"

semaphore = "#{project_root}/.valkyrie/cache/first_run_complete"

Vagrant.configure(2) do |config|
  require "#{valkyrie_root}/lib/load_config"
  conf = load_config()

  # Since we change the SSH user, we need to first install a public key. This
  # is done on the initial provisioning, which needs to run as the 'vagrant'
  # user. So, we switch based on the presence of a semaphore file, which we
  # create on provisioning, and remove after destroy.
  first_run = !File.file?(semaphore)

  config.trigger.after [:destroy] do
    # Remove semaphore file
    system "rm #{semaphore} > /dev/null 2>&1; echo '==> Removed semaphore file: #{semaphore}'"
  end

  require "#{valkyrie_root}/lib/drush_aliases"
  drush_aliases(config)

  require "#{valkyrie_root}/lib/vagrant-sshfs"
  if Vagrant.has_plugin? 'vagrant-sshfs'
    configure_vagrant_sshfs(config, conf)
  end

  require "#{valkyrie_root}/lib/vagrant-dns"
  if Vagrant.has_plugin? 'vagrant-dns'
    configure_vagrant_dns(config, conf)
  else
    install_vagrant_dns(config, conf)
    avahi_fallback(config, conf)
  end

  # Silence annoying and spurious warnings
  config.ssh.shell = 'bash -c "BASH_ENV=/etc/profile exec bash"'

  config.ssh.forward_agent = true

  config.vm.define 'default' do |vm1|

    vm1.vm.provider 'virtualbox' do |vbox|
      vbox.memory = '1024'
    end

    vm1.vm.box = 'hashicorp/precise64'

    vm1.vm.network 'private_network', ip: conf['ip']

    if first_run
      vm1.vm.provision 'file',
        source: '~/.ssh/id_rsa.pub',
        destination: '/vagrant/.valkyrie/ssh/authorized_keys'
    else
      # SSH as the 'aegir' user
      config.ssh.username = 'aegir'
      config.ssh.private_key_path = '~/.ssh/id_rsa'

      # Copy in some user-specific files to make the environment more familiar
      conf['dot_files'].each do |dot_file|
        real_dotfile = ENV['HOME']+'/'+dot_file
        if File.file?(real_dotfile)
          vm1.vm.provision 'file', source: real_dotfile,
            destination: "/var/aegir/#{dot_file}"
        end
      end
    end

    vm1.vm.provision 'puppet',
      module_path: "#{valkyrie_root}/lib/puppet/modules",
      manifests_path: "#{valkyrie_root}/lib/puppet/manifests",
      facter: { 'fqdn' => config.vm.hostname }

    config.trigger.after [:up] do
      # Run our file provisioning on the first run
      system "vagrant provision --provision-with=file"
    end

  end
end
