# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  #config.vm.box = "wheezy64"
  #config.vm.box_url = "http://dl.dropbox.com/u/937870/VMs/wheezy64.box"
  config.vm.box = "raring64"
  config.vm.box_url = "http://cloud-images.ubuntu.com/raring/current/raring-server-cloudimg-vagrant-amd64-disk1.box"

  config.vm.host_name = "aegir2.test"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "tests/functional_tests/aegir2"
    puppet.manifest_file = "nodes.pp"
    puppet.module_path = [ "tests/functional_tests/aegir2/modules" ]
  end

  # We can speed up subsequent rebuilds by caching the apt cache directories
  # on the host machine.
  config.vm.share_folder("apt_cache", "/var/cache/apt/archives", "tmp/apt/cache", :create => true)

end
